git server.port=8080

# --- BANCO DE DADOS (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/postgres
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- SEGURANÇA ---
spring.security.user.name=${SPRING_SECURITY_ADMIN_USER}
spring.security.user.password=${SPRING_SECURITY_ADMIN_PASS}

# --- CONFIGURAÇÃO DO JPA / HIBERNATE ---
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=false
spring.sql.init.mode=never

# --- FLYWAY ---
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration,classpath:db/seed

# --- TYPESENSE ---
typesense.host=${TYPESENSE_HOST}
typesense.port=${TYPESENSE_PORT}
typesense.protocol=${TYPESENSE_PROTOCOL}
typesense.api-key=${TYPESENSE_API_KEY}

# --- GEMINI (Google AI Studio) ---
langchain4j.google-ai-gemini.chat-model.api-key=${GEMINI_API_KEY}
langchain4j.google-ai-gemini.chat-model.model-name=gemini-3.6-flash
langchain4j.google-ai-gemini.chat-model.temperature=0.2